/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List accounts
         * @description Returns a paginated list of accounts.
         */
        get: operations["list-accounts"];
        put?: never;
        /**
         * Create account
         * @description Creates a new account.
         */
        post: operations["create-account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create transaction
         * @description Creates a new transaction.
         */
        post: operations["create-transaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transaction/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List transactions
         * @description Returns a paginated list of transactions using cursor-based pagination.
         */
        post: operations["list-transactions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /** @description Current decimal balance */
            balance: string;
            /** @description RFC3339 creation timestamp */
            createdAt: string;
            /** @description Account UUID */
            id: string;
            /** @description Account name */
            name: string;
            /** @description Initial decimal balance when account was created */
            startingBalance: string;
            /** @description Account sub-type */
            subType: string;
            /**
             * Format: int64
             * @description Account type: 0=Cash, 1=Credit Cards, 2=Investments, 3=Loans, 4=Assets
             */
            type: number;
        };
        CreateAccountBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateAccountBody.json
             */
            readonly $schema?: string;
            /** @description Account name */
            name: string;
            /** @description Starting balance as decimal string */
            startingBalance: string;
            /** @description Account sub-type */
            subType: string;
            /**
             * Format: int64
             * @description Account type (0=Cash, 1=CreditCards, 2=Investments, 3=Loans, 4=Assets)
             */
            type: number;
        };
        CreateTransactionBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateTransactionBody.json
             */
            readonly $schema?: string;
            /** @description Account UUID */
            accountID: string;
            /** @description Decimal amount */
            amount: string;
            /** @description Category UUID */
            categoryID: string;
            /** @description RFC3339 transaction date, defaults to now */
            transactionDate: string;
            /** @description Name of the transaction */
            transactionName: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ListAccountsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListAccountsResponseBody.json
             */
            readonly $schema?: string;
            /** @description Page of accounts */
            accounts: components["schemas"]["Account"][] | null;
            /** @description Cursor to fetch the next page, absent on the last page */
            nextCursor?: components["schemas"]["ListAccountsResponseBodyNextCursorStruct"];
        };
        ListAccountsResponseBodyNextCursorStruct: {
            /**
             * Format: int64
             * @description Page size
             */
            limit: number;
            /**
             * Format: int64
             * @description Offset for next page
             */
            position: number;
        };
        ListTransactionsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListTransactionsBody.json
             */
            readonly $schema?: string;
            /** @description Cursor from a previous response to fetch the next page */
            cursor?: components["schemas"]["ListTransactionsCursor"];
        };
        ListTransactionsCursor: {
            /**
             * Format: int64
             * @description Page size used for this cursor
             */
            limit: number;
            /**
             * Format: date-time
             * @description Upper bound on created_at locked in from the first page
             */
            maxCreationTime: string;
            /**
             * Format: int64
             * @description Numeric offset position for the next page
             */
            position: number;
        };
        ListTransactionsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListTransactionsResponseBody.json
             */
            readonly $schema?: string;
            /** @description Cursor to fetch the next page, absent on the last page */
            nextCursor?: components["schemas"]["ListTransactionsCursor"];
            /** @description Page of transactions */
            transactions: components["schemas"]["Transaction"][] | null;
        };
        Transaction: {
            /** @description Account UUID */
            accountID: string;
            /** @description Decimal amount */
            amount: string;
            /** @description Category UUID */
            categoryID: string;
            /** @description RFC3339 creation timestamp */
            createdAt: string;
            /** @description Transaction UUID */
            id: string;
            /** @description RFC3339 transaction date */
            transactionDate: string;
            /** @description Name of the transaction */
            transactionName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-accounts": {
        parameters: {
            query?: {
                /** @description Offset for pagination */
                position?: number;
                /** @description Page size, default 20 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAccountsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListTransactionsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTransactionsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
