name: Proto codegen

on:
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v4

      - run: pnpm install

      - name: buf generate
        run: pnpm generate

      - name: Check working tree
        run: git diff --exit-code src/gen
